{% set version = "4.2.13" %}

package:
  name: hdf4
  version: {{ version }}

source:
  url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-{{ version }}.tar.bz2
  sha256: 55d3a42313bda0aba7b0463687caf819a970e0ba206f5ed2c23724f80d2ae0f3
  patches:
    - max_files.patch

build:
  number: 2

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]
    - bison  # [not win]
    - flex  # [not win]
    - zlib
    - jpeg
  run:
    - zlib
    - jpeg

test:
  commands:
    - hdiff -V  # [not win]
    - h4_ncgen -V  # [not win]
    - h4_ncdump -V  # [not win]
    - test -f ${PREFIX}/lib/libdf.a  # [not win]
    - test -f ${PREFIX}/lib/libmfhdf.a  # [not win]
    - test -f ${PREFIX}/lib/libdf.so  # [linux]
    - test -f ${PREFIX}/lib/libdf.dylib  # [osx]
    - test -f ${PREFIX}/lib/libmfhdf.so  # [linux]
    - test -f ${PREFIX}/lib/libmfhdf.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.hdfgroup.org/HDF4/
  license: BSD 3-Clause
  summary: 'Library and multi-object file format for storing and managing data between machines.'
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - groutr
    - msarahan
    - ocefpaf
